# Generated by Django 4.1.4 on 2022-12-09 13:33

from django.db import migrations


def teacher_and_student(apps, schema_editor):
    Teacher = apps.get_model('school', 'Teacher')
    Student = apps.get_model('school', 'Student')
    for student in Student.objects.all():
        teacher = Teacher.objects.get(id=student.teacher_id)
        student.teachers.add(teacher)
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_teachers_alter_student_group_and_more'),
    ]

    operations = [
        migrations.RunPython(teacher_and_student, )
    ]
