# Generated by Django 4.1.4 on 2022-12-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
